### PR TITLE
fix(wait-for-job): add catch block and emit error

### LINKED ISSUE #623: Promise rejection error in waitForJob
We are running redis on AWS in cluster mode, which is returning this redis error when it swaps master/replica:
```
UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
```
That is then causing an error to throw in our bullmq services, full error:
```
ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
    at parseError (/code/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/code/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'bull:task:jobs:wait',
      'bull:task:jobs:active',
      '5'
    ]
  }
}
```

It seems that this try/finally is missing a catch causing this error to bubble up, would that be correct?
https://github.com/taskforcesh/bullmq/blob/220b4f619b30a8f04979e9abd0139e46d89b424d/src/classes/worker.ts#L241

### PR DESCRIPTION
**Pull request by roggervalf**
fixes #623

### CODE REVIEW

File: src/classes/worker.ts [hunk 1]
```diff
@@ -289,6 +292,11 @@ export class Worker<
         this.keys.active,
         opts.drainDelay,
       );
+    } catch (error) {
```
Comment (roggervalf) [inline src/classes/worker.ts:295]: don't really know how to make a test for this :thinking:

Comment (manast) [reply src/classes/worker.ts:295]: I think the only way to do it is by monkey patching ```client``` so that ```brpoplpush``` always throws an exception. So in the test overwrite this.blockingConnection.client with a stub. Sinon is the best for this, as we are already using it in other tests.

File: src/classes/worker.ts [hunk 2]
```diff
@@ -289,6 +292,11 @@ export class Worker<
...
+      if ((error as Error).message !== CONNECTION_CLOSED_ERROR_MSG) {
+        await delay(2000);
```
Comment (manast) [inline src/classes/worker.ts:297]: Just wondering, shouldn't we always delay? because otherwise if the error persists for a long time we will produce an endless loop here that may consume all CPU.
Also it would be great to refactor this magic number into a constant.

File: src/classes/worker.ts (hunk 1 above)
Comment (roggervalf) [reply src/classes/worker.ts:300]: so after adding the delay after if statement seems like in our test we are getting into that block, so I had to stub the delay method

File: src/test/test_repeat.ts [hunk 3]
```diff
@@ -323,7 +325,7 @@ describe('repeat', function() {
   });
 
   it('should remove repeated job when using removeOnComplete', async function() {
-    this.timeout(200000);
+    this.timeout(20000);
```
Comment (roggervalf) [inline src/test/test_repeat.ts:328]: these changes are because we are adding a higher number but we could choose a lower one in those cases, even when these changes are going to fail because of a change, test should not get stopped for too much time

File: src/classes/worker.ts [hunk 4]
```diff
@@ -289,12 +297,22 @@ export class Worker<
...
+        this.emit('error', error);
+      }
+      await this.delay();
     } finally {
       this.waiting = false;
     }
     return jobId;
   }
 
+  async delay(): Promise<void> {
```
Comment (roggervalf) [inline src/classes/worker.ts:312]: I need to do this in order to stub this function

Comment (manast) [reply src/classes/worker.ts:312]: Ok, but we can keep it private.

Comment (roggervalf) [reply src/classes/worker.ts:312]: when it is prívate I cannot stub it :/

Comment (manast) [reply src/classes/worker.ts:312]: aha, thats right. Then just a comment to explain why it is needed is enought.

**Review by manast — APPROVED** [review]

File: src/classes/redis-connection.ts [hunk 5]
```diff
@@ -150,7 +150,9 @@ export class RedisConnection extends EventEmitter {
           await this._client.quit();
         }
       } catch (error) {
-        handleError(error);
+        if (isNotConnectionError(error)) {
```
Comment (manast) [inline src/classes/redis-connection.ts:153]: Nice change. It is always better to have explicit functions instead of "handle" which can be anything. 👍
