### PR TITLE
fix(is-finished): reject when missing job key

### LINKED ISSUE #85: waitUntilFinished hang if removeOnComplete is set without TTL
When using the `removeOnComplete` option on a job, calling the `waitUntilFinished` will have an undefined behavior (unless ttl has been set).

If it's called before the job is cleared from the queue, it will work as intended but if the job is already removed, it will just hang indefinitely.

I think the `waitUntilFinished` function should warn the user if `removeOn...` is set as it may never resolve.

### PR DESCRIPTION
**Pull request by roggervalf**
fixes #85

### CODE REVIEW

File: src/classes/queue-events.ts [hunk 1]
```diff
@@ -244,7 +244,7 @@ export class QueueEvents extends QueueBase {
           }
         }
       } catch (err) {
-        if (err.message !== 'Connection is closed.') {
+        if ((err as Error).message !== 'Connection is closed.') {
```
Comment (manast) [inline src/classes/queue-events.ts:247]: Here we can use ```CONNECTION_CLOSED_ERROR_MSG``` from:
```ts
import { CONNECTION_CLOSED_ERROR_MSG } from 'ioredis/built/utils';

```

**Review by manast — CHANGES_REQUESTED** [review]
LGTM, just a small comment.

**Review by manast — APPROVED** [review]
