### PR TITLE
fix(worker): fix undefined moveToActive

### LINKED ISSUE #946: v1.57.4 client.moveToActive is not a function
Series issue with change client.moveToActive is not a function on recent upgrade.

TypeError: client.moveToActive is not a function
16/12/2021 13:32:26    at Function.moveToActive (/lokl/node_modules/bullmq/src/classes/scripts.ts:684:40)
16/12/2021 13:32:26    at processTicksAndRejections (internal/process/task_queues.js:95:5)

We have had to rollback our servers.

### PR DESCRIPTION
**Pull request by manast**
Fixes #946

### CODE REVIEW

File: src/classes/worker.ts [hunk 1]
```diff
@@ -694,6 +689,7 @@ export class Worker<
       try {
         return await fn();
       } catch (err) {
+        this.emit('error', <Error>err);
```
Comment (roggervalf) [inline src/classes/worker.ts:692]: Should we check if this is a connection error here?

**Review by roggervalf — APPROVED** [review]
LGTM just one question
