### PR TITLE
fix(worker): fix delayed jobs with concurrency fixes #1627

### LINKED ISSUE #1627: Delayed job is processed later than expected after upgrade to v2
**Description:**

Application adds a job with delay of 2s, but the worker starts to process it after around 5s (only first job is processed on time). Problem started after upgrade to v2.

It seems that there is something wrong with  `concurrency` option. When `concurrency: 1` then everything works well but with `concurrency: 2` it starts to process jobs after longer time. 

What is more, even if job is delayed with lower time, eg. 500ms then worker still starts to process job after around 5s.

**Code to reproduce the issue:**
```ts
import {Queue, Worker} from 'bullmq';

(async () => {
    const connectionOpts = {
        host: 'localhost',
        port: 6379,
    };

    new Worker(
        'my-queue', 
        async (job) => console.log(`Processing job ${job.id} at ${Date.now()}`),
        {connection: connectionOpts, concurrency: 2}
    );

    const myQueue = new Queue('my-queue', {connection: connectionOpts});

    while (true) {
        const job = await myQueue.add('my-queue', {foo: 'bar'}, {delay: 2000});
        console.log(`Added job ${job.id} at ${Date.now()}`);

        await new Promise(r => setTimeout(r, 10000));
    }
})();
```

Output:
```
Added job 56 at 1673862664113
Processing job 56 at 1673862666196

Added job 57 at 1673862674119
Processing job 57 at 1673862679123

Added job 58 at 1673862684121
Processing job 58 at 1673862689145

Added job 59 at 1673862694124
Processing job 59 at 1673862699166

Added job 60 at 1673862704127
Processing job 60 at 1673862709187

Added job 61 at 1673862714130
Processing job 61 at 1673862719209

Added job 62 at 1673862724131
Processing job 62 at 1673862729230
```

Change `concurrency: 1` and then the output will be like:
```
Added job 49 at 1673862557912
Processing job 49 at 1673862559986

Added job 50 at 1673862567916
Processing job 50 at 1673862570007

Added job 51 at 1673862577921
Processing job 51 at 1673862579928

Added job 52 at 1673862587926
Processing job 52 at 1673862589948

Added job 53 at 1673862597931
Processing job 53 at 1673862599969

Added job 54 at 1673862607934
Processing job 54 at 1673862609988

Added job 55 at 1673862617936
Processing job 55 at 1673862620010
```

**Versions:**
- bullmq 2.4.0
- node 16.14
- redis 6.2.6

### PR DESCRIPTION
**Pull request by manast**

### CODE REVIEW

File: tests/test_delay.ts [hunk 1]
```diff
@@ -274,6 +274,51 @@ describe('Delayed jobs', function () {
...
+
+    while (numJobs--) {
+      await queue.add('my-queue', { foo: 'bar' }, { delay });
+      await new Promise(r => setTimeout(r, 300));
+    }
+
+    await processing;
+
+    await worker.close();
+    await queue.close;
```
Comment (roggervalf) [inline tests/test_delay.ts]: Isn't a queue be declared in an beforeEach statememt?

**Review by roggervalf — APPROVED** [review]
LGTM
