### PR TITLE
fix(flow): correctly propagate jobId from pipeline results

### LINKED ISSUE #3878: [Bug]: Flow de-duplication behavior differs from regular jobs
### Version

v5.70.4

### Platform

NodeJS

### What happened?

When working with regular jobs, a de-duplicated job returns the same `job.id` as the original. This makes it easy to identify duplicates when using custom job IDs, e.g..

```node
const jobId = 'example';
const job = await queue.add(
	'example',
	{},
	{
		deduplication: { id: 'dedup' },
		jobId: jobId,
	}
);

if (job.id !== jobId) {
	console.log('Job has been de-duplicated');
}
```
 
However, this behavior does not carry over to flows. Is it expected that flows don’t return the same `job.id` when de-duplicated, unlike regular jobs?

### How to reproduce.

```node
const flow1 = await flow.add({
	name: 'example1',
	queueName: 'example',
	opts: {
		deduplication: { id: 'dedup' },
		delay: 500,
	},
});

const flow2 = await flow.add({
	name: 'example2',
	queueName: 'example',
	opts: {
		deduplication: { id: 'dedup' },
		delay: 500,
	},
});

if (flow1.job.id !== flow2.job.id) {
	throw new Error('Expected flow IDs to be the same');
}
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sohailfiza**
Fixes #3878

### Problem
When adding flows using FlowProducer, deduplicated jobs return incorrect job.id.
And Redis was correctly returning deduplicated jobId, but it was not propagated
back to the Job instances because multi.exec() results were not mapped.

### Soluution
Tracking command index for each job.addJob(multi) call. And after multi.exec() i mapped results to respective jobs and updated job.id with the actual value returned by redis.

### CODE REVIEW

File: src/classes/flow-producer.ts [hunk 1]
```diff
@@ -289,9 +302,12 @@ export class FlowProducer extends EventEmitter {
...
         });
 
-        const jobsTrees = await this.addNodes(multi, flows);
+        const jobsTrees = await this.addNodes(multi, flows, jobsToUpdate);
 
-        await multi.exec();
+        const results = (await multi.exec()) as
+          | [null | Error, string | number][]
+          | null;
+        this.updateJobIds(jobsToUpdate, results);
```
Comment (roggervalf) [inline src/classes/flow-producer.ts]: since this pr https://github.com/taskforcesh/bullmq/pull/3817 the only expected job to use deduplication option is the root parent job of a flow. No need to keep track of jobsToUpdate array if the only to be updated will be the root parent job

Comment (sohailfiza) [reply src/classes/flow-producer.ts]: Thanks, that makes sense. I’ll update the PR to only map the root job result.

Comment (sohailfiza) [reply src/classes/flow-producer.ts]: Updated the PR to only map root job ids after multi.exec(). Let me know if this looks good or if anything else should be adjusted.

**Comment by sohailfiza** [comment]
It looks like OSV scan failure is due to existing dependency vulnerabilities in repo. Should I address them in this PR.
